/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mangues_jni_helloword_NdkJniUtils */

#ifndef _Included_com_mangues_jni_helloword_NdkJniUtils
#define _Included_com_mangues_jni_helloword_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mangues_jni_helloword_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mangues_jni_1helloword_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_mangues_jni_1helloword_NdkJniUtils_generateKey(JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
